# ??? ?? ??? ??
debug: false

#end ???? ?? ????.
management:
  endpoints:
    web:
      exposure:
        include: "*"
#?? ??? ???.
logging:
  level:
    com.studio.projectboard: debug
    org.springframework.web.servlet: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  #DB?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: board-project-jm
    password: wjdals@@97
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #??? ??? ??? ???
    defer-datasource-initialization: true
    hibernate:
      #???? ddl?? ???. - ??
      ddl-auto: create
    open-in-view: false
    #sql?? ??
    show-sql: true
    properties:
      hibernate:
        #??? ??? ???? ???.
        format_sql: true
        #10?? ??? ??? ????.
        default_batch_fetch_size: 100
  #h2? ?? ????
  h2.console.enabled: false
  #??? ???? ?? ?? ?????. -> ??
  sql.init.mode: always

#123
  #data.rest:
    #base-path: /api
  #data:
    #rest:
      #detection-strategy: annotated
